[project]
name = "web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dropbox>=12.0.2",
    "dtw-python>=1.5.3",
    "jupyterlab>=4.3.4",
    "streamlit>=1.41.1",
    "streamlit-audiorecorder>=0.0.6",
]
